name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

env:
  REMOTE_PATH: /home/github/business-card
  REMOTE_HOST: 45.8.99.76
  REMOTE_USER: github

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Frontend Dependencies
        run: npm ci --prefix frontend
      - name: Build Frontend Files
        run: npm run build --prefix frontend
      - name: Update server files on remote host
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: --archive --compress --delete --exclude 'frontend'
          path: ./
          remote_path: $REMOTE_PATH
          remote_host: $REMOTE_HOST
          remote_user: $REMOTE_USER
          rmeote_key: ${{ secrets.DEPLOY_KEY }}
      - name: Update client files on remote host
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: --archive --compress --delete --exclude 'frontend'
          path: ./frontend/build/
          remote_path: $REMOTE_PATH/frontend/build
          remote_host: $REMOTE_HOST
          remote_user: $REMOTE_USER
          rmeote_key: ${{ secrets.DEPLOY_KEY }}
