name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

env:
  REMOTE_ROOT: github@45.8.99.76:/home/github/business-card

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up private SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_KEY }}
      - name: Install Frontend Dependencies
        run: npm ci --prefix frontend
      - name: Build Frontend Files
        run: npm run build --prefix frontend
      - name: Update server files on remote host
        run: rsync -e "ssh -o StrictHostKeyChecking=no" --archive --compress --delete --exclude 'frontend' . $REMOTE_ROOT
      - name: Update client files on remote host
        run: cd frontend/build && rsync -e "ssh -o StrictHostKeyChecking=no" --archive --compress --delete . $REMOTE_ROOT/frontend/build
